cloudProvider: "azure"

environmentVariables:
  LOG_LEVEL: "debug"

enabledFeatures:
  disableDryRun: true
  checkInterval: 120
  disableTTLCheck: false
  kubernetes: "in"
  s3: false

azureFeatures:
  azureRegions:
    - francecentral # Only need one region for Azure, it will check all regions
  rg: true
  acr: true
  storageAccount: true

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
