{{ range $mountedFile := .Values.mountedFiles -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: "pleco-{{ $mountedFile.name }}"
type: Opaque
data:
  content: |
    {{ $mountedFile.contentBase64 }}
{{ end }}